linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './.eslintrc.json'
    fixer: true
fixers:
    enable: true
files:
    ignore:
        - 'webroot/bower_components/*'
        - 'node_modules/*' 
        - 'no-unused-expressions'
        - 'box-model'
        - 'no-unused-vars'
        - 'no-undef'
        - 'unexpected token ='

 