linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './.eslintrc.json'
        fixer: true
   # csslint:
fixers:
   enable: true

files:
    ignore:
        - 'webroot/bower_components/*'
        - 'node_modules/*' 
        - 'no-unused-expressions'
        - 'box-model'
        - 'src/serviceWorker.js'